const colors = {
  light: {
    text: "#1B1B1B",
    tint: "#C89D29",
    background: "#FDF8EF",
    foreground: "#1B1B1B",
    card: "#FFFFFF",
    cardForeground: "#1B1B1B",
    primary: "#C89D29",
    primaryForeground: "#1B1B1B",
    secondary: "#E4D5B7",
    secondaryForeground: "#1B1B1B",
    muted: "#E4D5B7",
    mutedForeground: "#7A6A55",
    accent: "#1D4D4F",
    accentForeground: "#FDF8EF",
    destructive: "#AE1C1C",
    destructiveForeground: "#FFFFFF",
    border: "#D5C4A1",
    input: "#D5C4A1",
  },
  dark: {
    text: "#FDF8EF",
    tint: "#C89D29",
    background: "#1B1B1B",
    foreground: "#FDF8EF",
    card: "#252525",
    cardForeground: "#FDF8EF",
    primary: "#C89D29",
    primaryForeground: "#1B1B1B",
    secondary: "#2A2A2A",
    secondaryForeground: "#FDF8EF",
    muted: "#2A2A2A",
    mutedForeground: "#9A8A75",
    accent: "#1D4D4F",
    accentForeground: "#FDF8EF",
    destructive: "#AE1C1C",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#333333",
  },
  radius: 4,
};

export default colors;
